name: CI

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/actions/checkout@v4
      - uses: pnpm/actions/setup-@v4
        with:
          version: 9
      - run: pnpm install
      - run: pnpm lint
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/actions/checkout@v4
      - uses: pnpm/actions/setup-@v4
        with:
          version: 9
      - run: pnpm install
      - run: CI='false' pnpm build
